export const CryptoTaxCalculatorHeaders = [
  'Timestamp (UTC)',
  'Type',
  'Base Currency',
  'Base Amount',
  'Quote Currency (Optional)',
  'Quote Amount (Optional)',
  'Fee Currency (Optional)',
  'Fee Amount (Optional)',
  'From (Optional)',
  'To (Optional)',
  'Blockchain (Optional)',
  'ID (Optional)',
  'Description (Optional)',
  'Reference Price Per Unit (Optional)',
  'Reference Price Currency (Optional)',
]

export const GenericHeaders = [
  'ID',
  'Transaction',
  'Block',
  'Timestamp (UTC)',
  'Type',
  'From',
  'To',
  'Amount',
  'Memo',
  'Debit',
  'Credit',
  'Hive Running Total',
  'HBD Running Total',
  'Vests Running Total',
]
